<?php

namespace Database\Seeders;

use App\Models\Pays;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PaysTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                ['code' => 'AF', 'nom' => 'Afghanistan', 'indicatif' => '+93'],
                ['code' => 'ZA', 'nom' => 'Afrique du Sud', 'indicatif' => '+27'],
                ['code' => 'AL', 'nom' => 'Albanie', 'indicatif' => '+355'],
                ['code' => 'DZ', 'nom' => 'Algérie', 'indicatif' => '+213'],
                ['code' => 'DE', 'nom' => 'Allemagne', 'indicatif' => '+49'],
                ['code' => 'AD', 'nom' => 'Andorre', 'indicatif' => '+376'],
                ['code' => 'AO', 'nom' => 'Angola', 'indicatif' => '+244'],
                ['code' => 'AI', 'nom' => 'Anguilla', 'indicatif' => '+1'],
                ['code' => 'AQ', 'nom' => 'Antarctique', 'indicatif' => '+672'],
                ['code' => 'AG', 'nom' => 'Antigua-et-Barbuda', 'indicatif' => '+1'],
                ['code' => 'SA', 'nom' => 'Arabie saoudite', 'indicatif' => '+966'],
                ['code' => 'AR', 'nom' => 'Argentine', 'indicatif' => '+54'],
                ['code' => 'AM', 'nom' => 'Arménie', 'indicatif' => '+374'],
                ['code' => 'AW', 'nom' => 'Aruba', 'indicatif' => '+297'],
                ['code' => 'AU', 'nom' => 'Australie', 'indicatif' => '+61'],
                ['code' => 'AT', 'nom' => 'Autriche', 'indicatif' => '+43'],
                ['code' => 'AZ', 'nom' => 'Azerbaïdjan', 'indicatif' => '+994'],
                ['code' => 'BS', 'nom' => 'Bahamas', 'indicatif' => '+1'],
                ['code' => 'BH', 'nom' => 'Bahreïn', 'indicatif' => '+973'],
                ['code' => 'BD', 'nom' => 'Bangladesh', 'indicatif' => '+880'],
                ['code' => 'BB', 'nom' => 'Barbade', 'indicatif' => '+1'],
                ['code' => 'BY', 'nom' => 'Bélarus', 'indicatif' => '+375'],
                ['code' => 'BE', 'nom' => 'Belgique', 'indicatif' => '+32'],
                ['code' => 'BZ', 'nom' => 'Belize', 'indicatif' => '+501'],
                ['code' => 'BJ', 'nom' => 'Bénin', 'indicatif' => '+229'],
                ['code' => 'BM', 'nom' => 'Bermudes', 'indicatif' => '+1'],
                ['code' => 'BT', 'nom' => 'Bhoutan', 'indicatif' => '+975'],
                ['code' => 'BO', 'nom' => 'Bolivie', 'indicatif' => '+591'],
                ['code' => 'BA', 'nom' => 'Bosnie-Herzégovine', 'indicatif' => '+387'],
                ['code' => 'BW', 'nom' => 'Botswana', 'indicatif' => '+267'],
                ['code' => 'BR', 'nom' => 'Brésil', 'indicatif' => '+55'],
                ['code' => 'BN', 'nom' => 'Brunéi Darussalam', 'indicatif' => '+673'],
                ['code' => 'BG', 'nom' => 'Bulgarie', 'indicatif' => '+359'],
                ['code' => 'BF', 'nom' => 'Burkina Faso', 'indicatif' => '+226'],
                ['code' => 'BI', 'nom' => 'Burundi', 'indicatif' => '+257'],
                ['code' => 'KH', 'nom' => 'Cambodge', 'indicatif' => '+855'],
                ['code' => 'CM', 'nom' => 'Cameroun', 'indicatif' => '+237'],
                ['code' => 'CA', 'nom' => 'Canada', 'indicatif' => '+1'],
                ['code' => 'CV', 'nom' => 'Cap-Vert', 'indicatif' => '+238'],
                ['code' => 'CL', 'nom' => 'Chili', 'indicatif' => '+56'],
                ['code' => 'CN', 'nom' => 'Chine', 'indicatif' => '+86'],
                ['code' => 'CY', 'nom' => 'Chypre', 'indicatif' => '+357'],
                ['code' => 'CO', 'nom' => 'Colombie', 'indicatif' => '+57'],
                ['code' => 'KM', 'nom' => 'Comores', 'indicatif' => '+269'],
                ['code' => 'CG', 'nom' => 'Congo', 'indicatif' => '+242'],
                ['code' => 'CD', 'nom' => 'République Démocratique du Congo', 'indicatif' => '+243'],
                ['code' => 'KP', 'nom' => 'Corée du Nord', 'indicatif' => '+850'],
                ['code' => 'KR', 'nom' => 'Corée du Sud', 'indicatif' => '+82'],
                ['code' => 'CR', 'nom' => 'Costa Rica', 'indicatif' => '+506'],
                ['code' => 'CI', 'nom' => 'Côte d\'Ivoire', 'indicatif' => '+225'],
                ['code' => 'CF', 'nom' => 'République Centraficaine', 'indicatif' => '+236'],
                ['code' => 'HR', 'nom' => 'Croatie', 'indicatif' => '+385'],
                ['code' => 'CU', 'nom' => 'Cuba', 'indicatif' => '+53'],
                ['code' => 'CW', 'nom' => 'Curaçao', 'indicatif' => '+599'],
                ['code' => 'DK', 'nom' => 'Danemark', 'indicatif' => '+45'],
                ['code' => 'DJ', 'nom' => 'Djibouti', 'indicatif' => '+253'],
                ['code' => 'DM', 'nom' => 'Dominique', 'indicatif' => '+1'],
                ['code' => 'EG', 'nom' => 'Égypte', 'indicatif' => '+20'],
                ['code' => 'AE', 'nom' => 'Émirats arabes unis', 'indicatif' => '+971'],
                ['code' => 'EC', 'nom' => 'Équateur', 'indicatif' => '+593'],
                ['code' => 'ER', 'nom' => 'Érythrée', 'indicatif' => '+291'],
                ['code' => 'ES', 'nom' => 'Espagne', 'indicatif' => '+34'],
                ['code' => 'EE', 'nom' => 'Estonie', 'indicatif' => '+372'],
                ['code' => 'SZ', 'nom' => 'Eswatini', 'indicatif' => '+268'],
                ['code' => 'US', 'nom' => 'États-Unis', 'indicatif' => '+1'],
                ['code' => 'ET', 'nom' => 'Éthiopie', 'indicatif' => '+251'],
                ['code' => 'FJ', 'nom' => 'Fidji', 'indicatif' => '+679'],
                ['code' => 'FI', 'nom' => 'Finlande', 'indicatif' => '+358'],
                ['code' => 'FR', 'nom' => 'France', 'indicatif' => '+33'],
                ['code' => 'GA', 'nom' => 'Gabon', 'indicatif' => '+241'],
                ['code' => 'GM', 'nom' => 'Gambie', 'indicatif' => '+220'],
                ['code' => 'GE', 'nom' => 'Géorgie', 'indicatif' => '+995'],
                ['code' => 'GS', 'nom' => 'Géorgie du Sud et les îles Sandwich du Sud', 'indicatif' => '+500'],
                ['code' => 'GH', 'nom' => 'Ghana', 'indicatif' => '+233'],
                ['code' => 'GI', 'nom' => 'Gibraltar', 'indicatif' => '+350'],
                ['code' => 'GR', 'nom' => 'Grèce', 'indicatif' => '+30'],
                ['code' => 'GD', 'nom' => 'Grenade', 'indicatif' => '+1'],
                ['code' => 'GL', 'nom' => 'Groenland', 'indicatif' => '+299'],
                ['code' => 'GP', 'nom' => 'Guadeloupe', 'indicatif' => '+590'],
                ['code' => 'GU', 'nom' => 'Guam', 'indicatif' => '+1'],
                ['code' => 'GT', 'nom' => 'Guatemala', 'indicatif' => '+502'],
                ['code' => 'GG', 'nom' => 'Guernesey', 'indicatif' => '+44'],
                ['code' => 'GN', 'nom' => 'Guinée', 'indicatif' => '+224'],
                ['code' => 'GQ', 'nom' => 'Guinée équatoriale', 'indicatif' => '+240'],
                ['code' => 'GW', 'nom' => 'Guinée-Bissau', 'indicatif' => '+245'],
                ['code' => 'GY', 'nom' => 'Guyana', 'indicatif' => '+592'],
                ['code' => 'GF', 'nom' => 'Guyane française', 'indicatif' => '+594'],
                ['code' => 'HT', 'nom' => 'Haïti', 'indicatif' => '+509'],
                ['code' => 'HN', 'nom' => 'Honduras', 'indicatif' => '+504'],
                ['code' => 'HK', 'nom' => 'Hong Kong', 'indicatif' => '+852'],
                ['code' => 'HU', 'nom' => 'Hongrie', 'indicatif' => '+36'],
                ['code' => 'BV', 'nom' => 'Île Bouvet', 'indicatif' => '+47'],
                ['code' => 'CX', 'nom' => 'Île Christmas', 'indicatif' => '+61'],
                ['code' => 'AC', 'nom' => 'Île de l\'Ascension', 'indicatif' => '+247'],
                ['code' => 'IM', 'nom' => 'Île de Man', 'indicatif' => '+44'],
                ['code' => 'NF', 'nom' => 'Île Norfolk', 'indicatif' => '+672'],
                ['code' => 'KY', 'nom' => 'Îles Caïmans', 'indicatif' => '+1'],
                ['code' => 'CC', 'nom' => 'Îles Cocos (Keeling)', 'indicatif' => '+61'],
                ['code' => 'CK', 'nom' => 'Îles Cook', 'indicatif' => '+682'],
                ['code' => 'FO', 'nom' => 'Îles Féroé', 'indicatif' => '+298'],
                ['code' => 'HM', 'nom' => 'Îles Heard et MacDonald', 'indicatif' => '+672'],
                ['code' => 'FK', 'nom' => 'Îles Malouines (Falkland)', 'indicatif' => '+500'],
                ['code' => 'MP', 'nom' => 'Îles Mariannes du Nord', 'indicatif' => '+1'],
                ['code' => 'MH', 'nom' => 'Îles Marshall', 'indicatif' => '+692'],
                ['code' => 'UM', 'nom' => 'Îles mineures éloignées des États-Unis', 'indicatif' => '+1'],
                ['code' => 'SB', 'nom' => 'Îles Salomon', 'indicatif' => '+677'],
                ['code' => 'TC', 'nom' => 'Îles Turques-et-Caïques', 'indicatif' => '+1'],
                ['code' => 'VG', 'nom' => 'Îles Vierges britanniques', 'indicatif' => '+1'],
                ['code' => 'VI', 'nom' => 'Îles Vierges des États-Unis', 'indicatif' => '+1'],
                ['code' => 'IN', 'nom' => 'Inde', 'indicatif' => '+91'],
                ['code' => 'ID', 'nom' => 'Indonésie', 'indicatif' => '+62'],
                ['code' => 'IQ', 'nom' => 'Irak', 'indicatif' => '+964'],
                ['code' => 'IR', 'nom' => 'Iran', 'indicatif' => '+98'],
                ['code' => 'IE', 'nom' => 'Irlande', 'indicatif' => '+353'],
                ['code' => 'IS', 'nom' => 'Islande', 'indicatif' => '+354'],
                ['code' => 'IL', 'nom' => 'Israël', 'indicatif' => '+972'],
                ['code' => 'IT', 'nom' => 'Italie', 'indicatif' => '+39'],
                ['code' => 'JM', 'nom' => 'Jamaïque', 'indicatif' => '+1'],
                ['code' => 'JP', 'nom' => 'Japon', 'indicatif' => '+81'],
                ['code' => 'JE', 'nom' => 'Jersey', 'indicatif' => '+44'],
                ['code' => 'JO', 'nom' => 'Jordanie', 'indicatif' => '+962'],
                ['code' => 'KZ', 'nom' => 'Kazakhstan', 'indicatif' => '+7'],
                ['code' => 'KE', 'nom' => 'Kenya', 'indicatif' => '+254'],
                ['code' => 'KG', 'nom' => 'Kirghizistan', 'indicatif' => '+996'],
                ['code' => 'KI', 'nom' => 'Kiribati', 'indicatif' => '+686'],
                ['code' => 'XK', 'nom' => 'Kosovo', 'indicatif' => '+383'],
                ['code' => 'KW', 'nom' => 'Koweït', 'indicatif' => '+965'],
                ['code' => 'LA', 'nom' => 'Laos', 'indicatif' => '+856'],
                ['code' => 'LS', 'nom' => 'Lesotho', 'indicatif' => '+266'],
                ['code' => 'LV', 'nom' => 'Lettonie', 'indicatif' => '+371'],
                ['code' => 'LB', 'nom' => 'Liban', 'indicatif' => '+961'],
                ['code' => 'LR', 'nom' => 'Libéria', 'indicatif' => '+231'],
                ['code' => 'LY', 'nom' => 'Libye', 'indicatif' => '+218'],
                ['code' => 'LI', 'nom' => 'Liechtenstein', 'indicatif' => '+423'],
                ['code' => 'LT', 'nom' => 'Lituanie', 'indicatif' => '+370'],
                ['code' => 'LU', 'nom' => 'Luxembourg', 'indicatif' => '+352'],
                ['code' => 'MO', 'nom' => 'Macao', 'indicatif' => '+853'],
                ['code' => 'MG', 'nom' => 'Madagascar', 'indicatif' => '+261'],
                ['code' => 'MY', 'nom' => 'Malaisie', 'indicatif' => '+60'],
                ['code' => 'MW', 'nom' => 'Malawi', 'indicatif' => '+265'],
                ['code' => 'MV', 'nom' => 'Maldives', 'indicatif' => '+960'],
                ['code' => 'ML', 'nom' => 'Mali', 'indicatif' => '+223'],
                ['code' => 'MT', 'nom' => 'Malte', 'indicatif' => '+356'],
                ['code' => 'MA', 'nom' => 'Maroc', 'indicatif' => '+212'],
                ['code' => 'MQ', 'nom' => 'Martinique', 'indicatif' => '+596'],
                ['code' => 'MU', 'nom' => 'Maurice', 'indicatif' => '+230'],
                ['code' => 'MR', 'nom' => 'Mauritanie', 'indicatif' => '+222'],
                ['code' => 'YT', 'nom' => 'Mayotte', 'indicatif' => '+262'],
                ['code' => 'MX', 'nom' => 'Mexique', 'indicatif' => '+52'],
                ['code' => 'MD', 'nom' => 'Moldavie', 'indicatif' => '+373'],
                ['code' => 'MC', 'nom' => 'Monaco', 'indicatif' => '+377'],
                ['code' => 'MN', 'nom' => 'Mongolie', 'indicatif' => '+976'],
                ['code' => 'ME', 'nom' => 'Monténégro', 'indicatif' => '+382'],
                ['code' => 'MS', 'nom' => 'Montserrat', 'indicatif' => '+1'],
                ['code' => 'MZ', 'nom' => 'Mozambique', 'indicatif' => '+258'],
                ['code' => 'MM', 'nom' => 'Myanmar', 'indicatif' => '+95'],
                ['code' => 'NA', 'nom' => 'Namibie', 'indicatif' => '+264'],
                ['code' => 'NR', 'nom' => 'Nauru', 'indicatif' => '+674'],
                ['code' => 'NP', 'nom' => 'Népal', 'indicatif' => '+977'],
                ['code' => 'NI', 'nom' => 'Nicaragua', 'indicatif' => '+505'],
                ['code' => 'NE', 'nom' => 'Niger', 'indicatif' => '+227'],
                ['code' => 'NG', 'nom' => 'Nigeria', 'indicatif' => '+234'],
                ['code' => 'NU', 'nom' => 'Niue', 'indicatif' => '+683'],
                ['code' => 'NO', 'nom' => 'Norvège', 'indicatif' => '+47'],
                ['code' => 'NC', 'nom' => 'Nouvelle-Calédonie', 'indicatif' => '+687'],
                ['code' => 'NZ', 'nom' => 'Nouvelle-Zélande', 'indicatif' => '+64'],
                ['code' => 'IO', 'nom' => 'Territoire britannique de l\'océan Indien', 'indicatif' => '+246'],
                ['code' => 'OM', 'nom' => 'Oman', 'indicatif' => '+968'],
                ['code' => 'UG', 'nom' => 'Ouganda', 'indicatif' => '+256'],
                ['code' => 'UZ', 'nom' => 'Ouzbékistan', 'indicatif' => '+998'],
                ['code' => 'PK', 'nom' => 'Pakistan', 'indicatif' => '+92'],
                ['code' => 'PW', 'nom' => 'Palaos', 'indicatif' => '+680'],
                ['code' => 'PS', 'nom' => 'Palestine', 'indicatif' => '+970'],
                ['code' => 'PA', 'nom' => 'Panama', 'indicatif' => '+507'],
                ['code' => 'PG', 'nom' => 'Papouasie-Nouvelle-Guinée', 'indicatif' => '+675'],
                ['code' => 'PY', 'nom' => 'Paraguay', 'indicatif' => '+595'],
                ['code' => 'NL', 'nom' => 'Pays-Bas', 'indicatif' => '+31'],
                ['code' => 'PE', 'nom' => 'Pérou', 'indicatif' => '+51'],
                ['code' => 'PH', 'nom' => 'Philippines', 'indicatif' => '+63'],
                ['code' => 'PN', 'nom' => 'Pitcairn', 'indicatif' => '+64'],
                ['code' => 'PL', 'nom' => 'Pologne', 'indicatif' => '+48'],
                ['code' => 'PF', 'nom' => 'Polynésie française', 'indicatif' => '+689'],
                ['code' => 'PR', 'nom' => 'Porto Rico', 'indicatif' => '+1'],
                ['code' => 'PT', 'nom' => 'Portugal', 'indicatif' => '+351'],
                ['code' => 'QA', 'nom' => 'Qatar', 'indicatif' => '+974'],
                ['code' => 'MK', 'nom' => 'Macédoine du Nord', 'indicatif' => '+389'],
                ['code' => 'RO', 'nom' => 'Roumanie', 'indicatif' => '+40'],
                ['code' => 'GB', 'nom' => 'Royaume-Uni', 'indicatif' => '+44'],
                ['code' => 'RU', 'nom' => 'Russie', 'indicatif' => '+7'],
                ['code' => 'RW', 'nom' => 'Rwanda', 'indicatif' => '+250'],
                ['code' => 'EH', 'nom' => 'Sahara occidental', 'indicatif' => '+212'],
                ['code' => 'BL', 'nom' => 'Saint-Barthélemy', 'indicatif' => '+590'],
                ['code' => 'KN', 'nom' => 'Saint-Kitts-et-Nevis', 'indicatif' => '+1'],
                ['code' => 'SM', 'nom' => 'Saint-Marin', 'indicatif' => '+378'],
                ['code' => 'MF', 'nom' => 'Saint-Martin (partie française)', 'indicatif' => '+590'],
                ['code' => 'SX', 'nom' => 'Saint-Martin (partie néerlandaise)', 'indicatif' => '+1'],
                ['code' => 'PM', 'nom' => 'Saint-Pierre-et-Miquelon', 'indicatif' => '+508'],
                ['code' => 'VC', 'nom' => 'Saint-Vincent-et-les-Grenadines', 'indicatif' => '+1'],
                ['code' => 'SH', 'nom' => 'Sainte-Hélène', 'indicatif' => '+290'],
                ['code' => 'LC', 'nom' => 'Sainte-Lucie', 'indicatif' => '+1'],
                ['code' => 'SV', 'nom' => 'Salvador', 'indicatif' => '+503'],
                ['code' => 'WS', 'nom' => 'Samoa', 'indicatif' => '+685'],
                ['code' => 'AS', 'nom' => 'Samoa américaines', 'indicatif' => '+1'],
                ['code' => 'ST', 'nom' => 'Sao Tomé-et-Principe', 'indicatif' => '+239'],
                ['code' => 'SN', 'nom' => 'Sénégal', 'indicatif' => '+221'],
                ['code' => 'RS', 'nom' => 'Serbie', 'indicatif' => '+381'],
                ['code' => 'SC', 'nom' => 'Seychelles', 'indicatif' => '+248'],
                ['code' => 'SL', 'nom' => 'Sierra Leone', 'indicatif' => '+232'],
                ['code' => 'SG', 'nom' => 'Singapour', 'indicatif' => '+65'],
                ['code' => 'SK', 'nom' => 'Slovaquie', 'indicatif' => '+421'],
                ['code' => 'SI', 'nom' => 'Slovénie', 'indicatif' => '+386'],
                ['code' => 'SO', 'nom' => 'Somalie', 'indicatif' => '+252'],
                ['code' => 'SD', 'nom' => 'Soudan', 'indicatif' => '+249'],
                ['code' => 'SS', 'nom' => 'Soudan du Sud', 'indicatif' => '+211'],
                ['code' => 'LK', 'nom' => 'Sri Lanka', 'indicatif' => '+94'],
                ['code' => 'SE', 'nom' => 'Suède', 'indicatif' => '+46'],
                ['code' => 'CH', 'nom' => 'Suisse', 'indicatif' => '+41'],
                ['code' => 'SR', 'nom' => 'Suriname', 'indicatif' => '+597'],
                ['code' => 'SJ', 'nom' => 'Svalbard et Jan Mayen', 'indicatif' => '+47'],
                ['code' => 'SY', 'nom' => 'Syrie', 'indicatif' => '+963'],
                ['code' => 'TJ', 'nom' => 'Tadjikistan', 'indicatif' => '+992'],
                ['code' => 'TW', 'nom' => 'Taïwan', 'indicatif' => '+886'],
                ['code' => 'TZ', 'nom' => 'Tanzanie', 'indicatif' => '+255'],
                ['code' => 'TD', 'nom' => 'Tchad', 'indicatif' => '+235'],
                ['code' => 'CZ', 'nom' => 'Tchéquie', 'indicatif' => '+420'],
                ['code' => 'TF', 'nom' => 'Terres australes françaises', 'indicatif' => '+262'],
                ['code' => 'TH', 'nom' => 'Thaïlande', 'indicatif' => '+66'],
                ['code' => 'TL', 'nom' => 'Timor-Leste', 'indicatif' => '+670'],
                ['code' => 'TG', 'nom' => 'Togo', 'indicatif' => '+228'],
                ['code' => 'TK', 'nom' => 'Tokelau', 'indicatif' => '+690'],
                ['code' => 'TO', 'nom' => 'Tonga', 'indicatif' => '+676'],
                ['code' => 'TT', 'nom' => 'Trinité-et-Tobago', 'indicatif' => '+1'],
                ['code' => 'TN', 'nom' => 'Tunisie', 'indicatif' => '+216'],
                ['code' => 'TM', 'nom' => 'Turkménistan', 'indicatif' => '+993'],
                ['code' => 'TR', 'nom' => 'Turquie', 'indicatif' => '+90'],
                ['code' => 'TV', 'nom' => 'Tuvalu', 'indicatif' => '+688'],
                ['code' => 'UA', 'nom' => 'Ukraine', 'indicatif' => '+380'],
                ['code' => 'UY', 'nom' => 'Uruguay', 'indicatif' => '+598'],
                ['code' => 'VU', 'nom' => 'Vanuatu', 'indicatif' => '+678'],
                ['code' => 'VA', 'nom' => 'Vatican', 'indicatif' => '+379'],
                ['code' => 'VE', 'nom' => 'Venezuela', 'indicatif' => '+58'],
                ['code' => 'VN', 'nom' => 'Vietnam', 'indicatif' => '+84'],
                ['code' => 'WF', 'nom' => 'Wallis-et-Futuna', 'indicatif' => '+681'],
                ['code' => 'YE', 'nom' => 'Yémen', 'indicatif' => '+967'],
                ['code' => 'ZM', 'nom' => 'Zambie', 'indicatif' => '+260'],
                ['code' => 'ZW', 'nom' => 'Zimbabwe', 'indicatif' => '+263']
            ]
        ];

        foreach ($data as $item) {
            DB::table('pays')->insert($item);
        }
    }
}
