<?php

namespace Database\Seeders;

use App\Models\Repex;
use App\Models\Juridiction;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class RepexSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                ['codePays'=>'DZ', 'label'=>'Ambassade de Madagascar en Algerie', 'adr'=>'22, rue Abdelkar Aouis, Bologhine, Alger', 'email'=>''],
                ['codePays'=>'ZA', 'label'=>'Ambassade de Madagascar en Afrique du Sud', 'adr'=>'No 1, rue Blackwood, Arcadia, Pretoria', 'email'=>''],
                ['codePays'=>'DE', 'label'=>'Ambassade de Madagascar en Allemagne', 'adr'=>'Kurfürstendamm 72, 10709 Berlin', 'email'=>''],
                ['codePays'=>'SA', 'label'=>'Ambassade de Madagascar en Arabie Saoudite', 'adr'=>'Riyadh', 'email'=>''],
                ['codePays'=>'Be', 'label'=>'Ambassade de Madagascar en Belgique', 'adr'=>'Avenue de Tervuren 430, 1150 Bruxelles', 'email'=>''],
                ['codePays'=>'CA', 'label'=>'Ambassade de Madagascar au Canada', 'adr'=>'3, rue de Louvain, Ottawa, Ontario K1N 5M6', 'email'=>''],
                ['codePays'=>'CN', 'label'=>'Ambassade de Madagascar en Chine', 'adr'=>'No 8, Dong Wu Jie, San Li Tun, Beijing', 'email'=>''],
                ['codePays'=>'US', 'label'=>'Ambassade de Madagascar en Etats-Unis', 'adr'=>'Calle de la Pena de Francia 3, 28034 Madrid', 'email'=>''],
                ['codePays'=>'ET', 'label'=>'Ambassade de Madagascar en Ethiopie', 'adr'=>'', 'email'=>''],
                ['codePays'=>'FR', 'label'=>'Ambassade de Madagascar en France', 'adr'=>'4, avenue Raphaël, 75016 Paris', 'email'=>''],
                ['codePays'=>'MU', 'label'=>'Ambassade de Madagascar à Maurice','adr'=>'MU, Guiot Pasceau, 74101, Maurice','email'=>''],
                ['codePays'=>'IN', 'label'=>'Ambassade de Madagascar en Inde', 'adr'=>'No 65, Paschimi Marg, Vasant Vihar, New Delhi', 'email'=>''],
                ['codePays'=>'IT', 'label'=>'Ambassade de Madagascar en Italie', 'adr'=>'Via Orazio 3, 00193 Rome', 'email'=>''],
                ['codePays'=>'JP', 'label'=>'Ambassade de Madagascar au Japon', 'adr'=>'No 50, Kowa Building, 9th Floor, 4-12', 'email'=>''],
                ['codePays'=>'MA', 'label'=>'Ambassade de Madagascar au Maroc', 'adr'=>'', 'email'=>''],
                ['codePays'=>'CH', 'label'=>'Ambassade de Madagascar en Suisse', 'adr'=>'Avenue de Riant-Parc 38, 1209 Genève, Suisse', 'email'=>''],
                ['codePays'=>'GB', 'label'=>'Ambassade de Madagascar en Grande Bretagne', 'adr'=>'8, Leinster Square, Bayswater, London W2 4PR', 'email'=>''],
                ['codePays'=>'RU', 'label'=>'Ambassade de Madagascar en Russie', 'adr'=>'Kursovoy Pereulok, 5, Moscow, Russie, 119091', 'email'=>''],
                ['codePays'=>'SN', 'label'=>'Ambassade de Madagascar au Sénégal', 'adr'=>'BP 25.395 Dakar Fann Imm Royal Building 2e étage, Almadies Zone 16 Dakar, 10700, Sénégal', 'email'=>''],
            ]

            ];

            foreach ($data as $item) {
                DB::table('repexes')->insert($item);
            }

        $dataJuridication = [
            [
                ['repexId' => 1, 'codePays' => 'DZ'],
                ['repexId' => 1, 'codePays' => 'TN'],
                ['repexId' => 1, 'codePays' => 'LY'],
                ['repexId' => 1, 'codePays' => 'MR'],
                ['repexId' => 2, 'codePays' => 'MW'],
                ['repexId' => 2, 'codePays' => 'ZA'],
                ['repexId' => 2, 'codePays' => 'MZ'],
                ['repexId' => 2, 'codePays' => 'NA'],
                ['repexId' => 2, 'codePays' => 'BW'],
                ['repexId' => 2, 'codePays' => 'ZW'],
                ['repexId' => 2, 'codePays' => 'ZM'],
                ['repexId' => 2, 'codePays' => 'AD'],
                ['repexId' => 2, 'codePays' => 'LS'],
                ['repexId' => 2, 'codePays' => 'SZ'],
                ['repexId' => 2, 'codePays' => 'TZ'],
                ['repexId' => 2, 'codePays' => 'CG'],
                ['repexId' => 2, 'codePays' => 'RW'],
                ['repexId' => 2, 'codePays' => 'BI'],
                ['repexId' => 3, 'codePays' => 'DE'],
                ['repexId' => 3, 'codePays' => 'DK'],
                ['repexId' => 3, 'codePays' => 'IS'],
                ['repexId' => 3, 'codePays' => 'AT'],
                ['repexId' => 3, 'codePays' => 'PL'],
                ['repexId' => 3, 'codePays' => 'CZ'],
                ['repexId' => 3, 'codePays' => 'sk'],
                ['repexId' => 3, 'codePays' => 'HU'],
                ['repexId' => 3, 'codePays' => 'LT'],
                ['repexId' => 3, 'codePays' => 'EE'],
                ['repexId' => 4, 'codePays' => 'BH'],
                ['repexId' => 4, 'codePays' => 'AE'],
                ['repexId' => 4, 'codePays' => 'OM'],
                ['repexId' => 4, 'codePays' => 'JO'],
                ['repexId' => 4, 'codePays' => 'SY'],
                ['repexId' => 4, 'codePays' => 'YE'],
                ['repexId' => 4, 'codePays' => 'LB'],
                ['repexId' => 4, 'codePays' => 'IQ'],
                ['repexId' => 4, 'codePays' => 'QA'],
                ['repexId' => 4, 'codePays' => 'KW'],
                ['repexId' => 5, 'codePays' => 'BE'],
                ['repexId' => 5, 'codePays' => 'NL'],
                ['repexId' => 5, 'codePays' => 'LU'],
                ['repexId' => 6, 'codePays' => 'CA'],
                ['repexId' => 6, 'codePays' => 'CU'],
                ['repexId' => 6, 'codePays' => 'HT'],
                ['repexId' => 6, 'codePays' => 'DM'],
                ['repexId' => 6, 'codePays' => 'JM'],
                ['repexId' => 6, 'codePays' => 'TT'],
                ['repexId' => 6, 'codePays' => 'BS'],
                ['repexId' => 6, 'codePays' => 'BZ'],
                ['repexId' => 6, 'codePays' => 'BB'],
                ['repexId' => 6, 'codePays' => 'VC'],
                ['repexId' => 6, 'codePays' => 'GD'],
                ['repexId' => 6, 'codePays' => 'AG'],
                ['repexId' => 6, 'codePays' => 'KY'],
                ['repexId' => 6, 'codePays' => 'KN'],
                ['repexId' => 6, 'codePays' => 'TC'],
                ['repexId' => 6, 'codePays' => 'SX'],
                ['repexId' => 6, 'codePays' => 'AI'],
                ['repexId' => 6, 'codePays' => 'BL'],
                ['repexId' => 7, 'codePays' => 'CN'],
                ['repexId' => 7, 'codePays' => 'LA'],
                ['repexId' => 7, 'codePays' => 'KH'],
                ['repexId' => 7, 'codePays' => 'VN'],
                ['repexId' => 7, 'codePays' => 'MN'],
                ['repexId' => 7, 'codePays' => 'MM'],
                ['repexId' => 7, 'codePays' => 'TH'],
                ['repexId' => 8, 'codePays' => 'US'],
                ['repexId' => 8, 'codePays' => 'CO'],
                ['repexId' => 8, 'codePays' => 'BR'],
                ['repexId' => 8, 'codePays' => 'MX'],
                ['repexId' => 8, 'codePays' => 'CL'],
                ['repexId' => 8, 'codePays' => 'AR'],
                ['repexId' => 8, 'codePays' => 'PE'],
                ['repexId' => 8, 'codePays' => 'PY'],
                ['repexId' => 8, 'codePays' => 'UY'],
                ['repexId' => 8, 'codePays' => 'VE'],
                ['repexId' => 8, 'codePays' => 'EC'],
                ['repexId' => 8, 'codePays' => 'BO'],
                ['repexId' => 8, 'codePays' => 'GY'],
                ['repexId' => 8, 'codePays' => 'SR'],
                ['repexId' => 9, 'codePays' => 'ET'],
                ['repexId' => 9, 'codePays' => 'EG'],
                ['repexId' => 9, 'codePays' => 'KE'],
                ['repexId' => 9, 'codePays' => 'SD'],
                ['repexId' => 9, 'codePays' => 'DJ'],
                ['repexId' => 9, 'codePays' => 'UG'],
                ['repexId' => 9, 'codePays' => 'ER'],
                ['repexId' => 9, 'codePays' => 'SO'],
                ['repexId' => 9, 'codePays' => 'CM'],
                ['repexId' => 9, 'codePays' => 'TD'],
                ['repexId' => 9, 'codePays' => 'SS'],
                ['repexId' => 9, 'codePays' => 'CF'],
                ['repexId' => 9, 'codePays' => 'GA'],
                ['repexId' => 9, 'codePays' => 'CD'],
                ['repexId' => 9, 'codePays' => 'IR'],
                ['repexId' => 10, 'codePays' => 'FR'],
                ['repexId' => 10, 'codePays' => 'ES'],
                ['repexId' => 10, 'codePays' => 'IL'],
                ['repexId' => 10, 'codePays' => 'MC'],
                ['repexId' => 10, 'codePays' => 'PT'],
                ['repexId' => 10, 'codePays' => 'XK'],
                ['repexId' => 11, 'codePays' => 'MU'],
                ['repexId' => 11, 'codePays' => 'BD'],
                ['repexId' => 11, 'codePays' => 'SC'],
                ['repexId' => 11, 'codePays' => 'PK'],
                ['repexId' => 11, 'codePays' => 'SB'],
                ['repexId' => 11, 'codePays' => 'AU'],
                ['repexId' => 11, 'codePays' => 'NZ'],
                ['repexId' => 11, 'codePays' => 'TL'],
                ['repexId' => 12, 'codePays' => 'IN'],
                ['repexId' => 12, 'codePays' => 'LK'],
                ['repexId' => 12, 'codePays' => 'NP'],
                ['repexId' => 12, 'codePays' => 'MV'],
                ['repexId' => 12, 'codePays' => 'BT'],
                ['repexId' => 12, 'codePays' => 'AF'],
                ['repexId' => 13, 'codePays' => 'IT'],
                ['repexId' => 13, 'codePays' => 'AL'],
                ['repexId' => 13, 'codePays' => 'RO'],
                ['repexId' => 13, 'codePays' => 'CY'],
                ['repexId' => 13, 'codePays' => 'BG'],
                ['repexId' => 13, 'codePays' => 'MD'],
                ['repexId' => 13, 'codePays' => 'GE'],
                ['repexId' => 13, 'codePays' => 'AM'],
                ['repexId' => 13, 'codePays' => 'GR'],
                ['repexId' => 13, 'codePays' => 'TR'],
                ['repexId' => 13, 'codePays' => 'SM'],
                ['repexId' => 13, 'codePays' => 'SI'],
                ['repexId' => 13, 'codePays' => 'HR'],
                ['repexId' => 13, 'codePays' => 'BA'],
                ['repexId' => 13, 'codePays' => 'MK'],
                ['repexId' => 13, 'codePays' => 'ME'],
                ['repexId' => 14, 'codePays' => 'JP'],
                ['repexId' => 14, 'codePays' => 'SG'],
                ['repexId' => 14, 'codePays' => 'KR'],
                ['repexId' => 14, 'codePays' => 'ID'],
                ['repexId' => 14, 'codePays' => 'BN'],
                ['repexId' => 14, 'codePays' => 'PG'],
                ['repexId' => 14, 'codePays' => 'MY'],
                ['repexId' => 14, 'codePays' => 'PH'],
                ['repexId' => 15, 'codePays' => 'MA'],
                ['repexId' => 15, 'codePays' => 'CV'],
                ['repexId' => 15, 'codePays' => 'ML'],
                ['repexId' => 15, 'codePays' => 'NG'],
                ['repexId' => 15, 'codePays' => 'BF'],
                ['repexId' => 16, 'codePays' => 'CH'],
                ['repexId' => 17, 'codePays' => 'GB'],
                ['repexId' => 17, 'codePays' => 'FO'],
                ['repexId' => 17, 'codePays' => 'FI'],
                ['repexId' => 17, 'codePays' => 'SE'],
                ['repexId' => 17, 'codePays' => 'NO'],
                ['repexId' => 17, 'codePays' => 'IE'],
                ['repexId' => 18, 'codePays' => 'RU'],
                ['repexId' => 18, 'codePays' => 'KZ'],
                ['repexId' => 18, 'codePays' => 'KG'],
                ['repexId' => 18, 'codePays' => 'LV'],
                ['repexId' => 18, 'codePays' => 'RS'],
                ['repexId' => 18, 'codePays' => 'UZ'],
                ['repexId' => 18, 'codePays' => 'TM'],
                ['repexId' => 18, 'codePays' => 'UA'],
                ['repexId' => 18, 'codePays' => 'TJ'],
                ['repexId' => 18, 'codePays' => 'BY'],
                ['repexId' => 18, 'codePays' => 'AZ'],
                ['repexId' => 19, 'codePays' => 'SN'],
                ['repexId' => 19, 'codePays' => 'GM'],
                ['repexId' => 19, 'codePays' => 'CI'],
                ['repexId' => 19, 'codePays' => 'GH'],
                ['repexId' => 19, 'codePays' => 'GQ'],
                ['repexId' => 19, 'codePays' => 'NE'],
                ['repexId' => 19, 'codePays' => 'SL'],
                ['repexId' => 19, 'codePays' => 'TG'],
                ['repexId' => 19, 'codePays' => 'LR'],
                ['repexId' => 19, 'codePays' => 'BJ'],
                ['repexId' => 19, 'codePays' => 'GW'],
                ['repexId' => 19, 'codePays' => 'ST'],
                ['repexId' => 19, 'codePays' => 'GN'],
            ]
            ];

            foreach ($dataJuridication as $item) {
                DB::table('juridictions')->insert($item);
            }
    }
}
